import 'package:get/get.dart';

class local implements Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    "ar" : {
      "title1" : "صباح الخير",
      "desc1" : "انضم إلى مهمتنا لجعل الرعاية الصحية في متناول الجميع.تبرع بالدم، ابحث عن الصيدليات، واعتنِ بصحتك، كل ذلك في تطبيق واحد",
      "title2" : "التبرع بالدم ببساطة",
      "desc2" : "سجل كمتبرع بالدم أو اطلب الدم في حالات الطوارئ. معًا، يمكننا إنقاذ الأرواح ببضع نقرات فقط.",
      "title3" : "مساعدك الشخصي",
      "desc3" : "استخدم تحليل الأشعة السينية المدعوم بالذكاء الاصطناعي وروبوت الدردشة الطبي للحصول على رؤى صحية فورية ونصائح طبية.",
      "title4" : "تحديد الموقع والخدمات القريبة",
      "desc4" : "احجز مواعيد في العيادات القريبة أو اعثر على أقرب صيدلية بكل سهولة. الرعاية الصحية الآن على بُعد خطوات منك!",
      "title5" : "كن منظمًا واحصل على نقاط!",
      "desc5" : "قم بضبط التذكيرات، وتتبع المواعيد، واحصل على نقاط مقابل استخدام التطبيق لاستبدالها بمكافآت رائعة!",
      "button" : "ابدأ الآن",
      "login" : "تسجيل الدخول",
      "email" : "البريد الإلكتروني",
      "password" : "كلمة المرور",
      "forget" : "هل نسيت كلمة المرور؟",
      "createAcc" : "إنشاء حساب جديد",
      "regName" : "الاسم",
      "regEmail" : "البريد الإلكتروني",
      "regPhone" : "رقم الهاتف",
      "regPassword" : "كلمة المرور",
      "regPassconfirm" : "تأكيد كلمة المرور",
      "regButton" : "تسجيل الحساب",
      "HaveAccount" : "لدي حساب بالفعل",
      "setAccount" : "إعداد حسابك",
      "BloodTyp" : "فصيلة الدم",
      "Weight" : "الوزن",
      "Height" : "الطول",
      "Age" : "العمر",
      "finishButton" : "إتمام",
      "Guest" : "زائر",
      "GoodNight" : "تصبح على خير",
      "GoodMorning" : "صباح الخير",
      "Doctors" : "الأطباء",
      "viewAll" : "عرض الكل",
      "xRay" : "فحص الأشعة\nالسينية الخاصة\nبك",
      "chatBot" : "سبيرا بوت",
      "Medic" : "الأدوية",
      "bloodDonation" : "التبرع بالدم",
      "donationHistory" : "سجل التبرعات",
      "noDonation" : "لا يوجد سجل للتبرعات",
      "donate" : "تبرع",
      "donationStation" : "محطة التبرع",
      "qrDonate" : "تبرع",
      "scanButton" : "مسح",
      "Stations" : "المحطات",
      "Stationslocation" : "موقعك هو",
      "medicalNews" : "أخبار طبية",
      "Reminder" : "تذكير",
      "allReminders" : "جميع التذكيرات",
      "addReminder" : "إضافة تذكير",
      "medicineName" : "اسم الدواء",
      "Details" : "التفاصيل",
      "noTime" : "لم يتم تحديد الوقت",
      "Add" : "إضافة",
      "selectedTime" : "الوقت المحدد",
      // "profAge" : "العمر",
      // "profPoints" : "النقاط",
      // "profDonations" : "التبرعات",
      // "Logout" : "تسجيل الخروج",
      // "profBloodType" : "فصيلة الدم",
      // "profHeight" : "الطول",
      // "profWeight" : "الوزن",
      //



    },


    "de" : {
      "title1" : "Guten Morgen",
      "desc1" : "Schließe dich unserer Mission an, um Gesundheitsversorgung für alle zugänglich zu machen. Spende Blut, finde Apotheken und verwalte deine Gesundheit – alles in einer App.",
      "title2" : "Vereinfachte Blutspende",
      "desc2" : "Registriere dich als Blutspender oder fordere Blut in Notfällen an. Gemeinsam können wir mit nur wenigen Klicks Leben retten.",
      "title3" : "Dein persönlicher Assistent",
      "desc3" : "Nutze KI-gestützte Röntgenanalyse und einen medizinischen Chatbot, um sofortige Einblicke in deine Gesundheit und Ratschläge zu erhalten.",
      "title4" : "Finde & Nahegelegene Dienste",
      "desc4" : "Buche Termine in nahegelegenen Kliniken oder finde die nächste Apotheke ganz einfach. Gesundheitsversorgung ist jetzt in deiner Nähe!",
      "title5" : "Bleibe organisiert & sammle Punkte",
      "desc5" : "Setze Erinnerungen, verfolge Termine und sammle Punkte für die Nutzung der App, um spannende Belohnungen einzulösen!",
      "button" : "Loslegen",
      "login" : "Anmelden",
      "email" : "E-Mail",
      "password" : "Passwort",
      "forget" : "Passwort vergessen?",
      "createAcc" : "Neuen Account erstellen",
      "regName" : "Name",
      "regEmail" : "E-Mail",
      "regPhone" : "Telefonnummer",
      "regPassword" : "Passwort",
      "regPassconfirm" : "Passwort bestätigen",
      "regButton" : "Registrieren",
      "HaveAccount" : "Hast du bereits einen Account?",
      "setAccount" : "Richte deinen Account ein",
      "BloodTyp" : "Blutgruppe",
      "Weight" : "Gewicht",
      "Height" : "Größe",
      "Age" : "Alter",
      "finishButton" : "Fertigstellen",
      "Guest" : "Gast",
      "GoodNight" : "Gute Nacht",
      "GoodMorning" : "Guten Morgen",
      "Doctors" : "Ärzte",
      "viewAll" : "Alle ansehen",
      "xRay" : "Überprüfe\nDeine\nRöntgenbilder",
      "chatBot" : "Spera Bot",
      "Medic" : "Medikamente",
      "bloodDonation" : "Blutspende",
      "donationHistory" : "Spendenverlauf",
      "noDonation" : "Keine Spendenhistorie verfügbar",
      "donate" : "Spenden",
      "donationStation" : "Spendenstation",
      "qrDonate" : "Spenden",
      "scanButton" : "Scannen",
      "Stations" : "Stationen",
      "Stationslocation" : "Dein Standort ist",
      "medicalNews" : "Medizinische Nachrichten",
      "Reminder" : "Erinnerung",
      "allReminders" : "Alle Erinnerungen",
      "addReminder" : "Erinnerung hinzufügen",
      "medicineName" : "Medikamentenname",
      "Details" : "Details",
      "noTime" : "Keine Zeit ausgewählt",
      "Add" : "Hinzufügen",
      "selectedTime" : "Ausgewählte Zeit"
    },


    "eng" : {
      "title1" : "Good morning",
      "desc1" : "Join our mission to make healthcare accessible for everyone. Donate blood, find pharmacies, and manage your health all in one app",
      "title2" : "Simplified Blood Donation",
      "desc2" : "Register as a blood donor or request blood in emergencies. Together, we can save lives with just a few clicks",
      "title3" : "Your Personal assistant",
      "desc3" : "Use AI-powered X-ray analysis and a medical chat bot to get instant health insights and advice.",
      "title4" : "Locate & Nearby Services",
      "desc4" : "Book appointments at nearby clinics or locate the closest pharmacy with ease. Healthcare is now just around the corner!",
      "title5" : "Stay Organized & Earn Points",
      "desc5" : "Set reminders, track appointments, and earn points for app engagement to redeem exciting rewards!",
      "button" : "Get Started",
      "login" : "Login",
      "email" : "Email",
      "password" : "Password",
      "forget" : "Forget password?",
      "createAcc" : "Create New Acount",
      "regName" : "Name",
      "regEmail" : "Email",
      "regPhone" : "Phone number",
      "regPassword" : "Password",
      "regPassconfirm" : "Confirm Password",
      "regButton" : "Register",
      "HaveAccount" : "Already Have An Account",
      "setAccount" : "Setup Your Account",
      "BloodTyp" : "Blood Type",
      "Weight" : "Weight",
      "Height" : "Height",
      "Age" : "Age",
      "finishButton" : "Finish",
      "Guest" : "Guest",
      "GoodNight" : "Good night",
      "GoodMorning" : "Good morning",
      "Doctors" : "Doctors",
      "viewAll" : "View All",
      "xRay" : "Check\nYour\nX-Rays",
      "chatBot" : "Spera Bot",
      "Medic" : "Medicines",
      "bloodDonation" : "Blood Donation",
      "donationHistory" : "Donation History",
      "noDonation" : "No donation history available",
      "donate" : "Donate",
      "donationStation" : "Donation Station",
      "qrDonate" : "Donate",
      "scanButton" : "Scan",
      "Stations" : "Stations",
      "Stationslocation" : "Your Location is",
      "medicalNews" : "Medical News",
      "Reminder" : "Reminder",
      "allReminders" : "All Reminders",
      "addReminder" : "Add Reminder",
      "medicineName" : "Medicine name",
      "Details" : "Details",
      "noTime" : "No time selected",
      "Add" : "Add",
      "selectedTime" : "Selected time",
      // "profAge" : "Age",
      // "profPoints" : "Points",
      // "profDonations" : "Donations",
      // "Logout" : "Logout",
      // "profBloodType" : "Blood Type",
      // "profHeight" : "Height",
      // "profWeight" : "Weight",


    },



  };

}